name: Update fallback.json (hourly)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"  # every hour

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate fallback.json
        run: |
          python scripts/generate.py

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain fallback.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add fallback.json
            git commit -m "chore: update fallback.json"
            git push
          else
            echo "No changes to commit."
          fi
